# Common settings supported by Windows OpenSSH Client.
Host *
  UpdateHostKeys                yes
  PreferredAuthentications      publickey,keyboard-interactive,password
  ConnectTimeout                5
  ConnectionAttempts            3
  ServerAliveInterval           50
  ServerAliveCountMax           5

Match originalhost *-r,*-r-*
  RemoteForward                 52698 localhost:52698
  ExitOnForwardFailure          yes

Match originalhost *-debug,*-debug-*
  LogLevel                      DEBUG

Host *github*
  HostName                      ssh.github.com
  Port                          443
  User                          git
