# - ----------------------------------------------------------------------------
# - Node
# - ----------------------------------------------------------------------------
# - options                     parameters


# - ----------------------------------------------------------------------------
# - Defaults
# - ----------------------------------------------------------------------------
# - options                     parameters
Host dev.*
  StrictHostKeyChecking         no
  UserKnownHostsFile            /dev/null
  GlobalKnownHostsFile          /dev/null
